# Generated by Django 5.0 on 2023-12-09 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AudioData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('location', models.CharField(max_length=255)),
                ('edu', models.CharField(max_length=255)),
                ('audio', models.FileField(upload_to='audio_files/')),
            ],
        ),
    ]
