# Generated by Django 5.0 on 2024-01-21 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='audiodata',
            name='last_modified',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='audiodata',
            name='size',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='audiodata',
            name='type',
            field=models.CharField(default=0, max_length=50),
        ),
    ]
