# Generated by Django 5.0 on 2024-01-21 07:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recorder', '0002_audiodata_last_modified_audiodata_size_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='audiodata',
            name='last_modified',
        ),
        migrations.RemoveField(
            model_name='audiodata',
            name='size',
        ),
        migrations.RemoveField(
            model_name='audiodata',
            name='type',
        ),
    ]
